top-level: use callPackages where inheriting packages
otherwise those packages cannot be overriden

nix-repl> nomad.override
error: attribute 'override' missing

       at «string»:1:1:

            1| nomad.override
             | ^

With this change they can be overriden

nix-repl> nomad.override
{ __functionArgs = { ... }; __functor = «lambda @ /home/sandro/src/nixpkgs2/lib/trivial.nix:440:19»; }

Resubmition because of revert in #281932 because of an oversight of me.

I tested this with

NIXPKGS_ALLOW_UNFREE=1 NIXPKGS_ALLOW_NONSOURCE=1 NIXPKGS_ALLOW_BROKEN=1 nix build --impure .#prefetch-yarn-deps .#python3Packages.dash .#ivpn .#ivpn-service .#charles3 .#charles4 .#msrtool .#cbmem .#ifdtool .#intelmetool .#cbfstool .#nvramtool .#superiotool .#ectool .#inteltool .#amdfwtool .#acpidump-all .#coreboot-utils .#garage .#garage_0_8 .#garage_0_9 .#garage_0_8_4 .#garage_0_9_0 .#nextcloud26 .#nextcloud27 .#nextcloud28 .#nomad .#nomad_1_4 .#nomad_1_5 .#nomad_1_6 .#nomad_1_7